### ISSUE TITLE
FR: Fix local device conflicts by using ARP who-has packets

### ISSUE THREAD

**Issue by ionizer999** [zhuyifei1999/ishoal#3]
While rooms (#2) will allow to easily detect conflicts of other players, there is still the problem with local device conflicts.

Those can be solved by checking whenever a node joins if any other node in the network would get a local reply on that IP address.

There are 2 cases:

- Node joins newly and has the same IP as some device in someone else's subnet
- Node joins newly and a device in the network has the same IP as one of the existing IPs already

A larger problem however are devices that are added to the network dynamically as one would need to constantly check for ARP packets.

=> Maybe router method with e.g. 17.99.*.* or 192.168.99.* subnet might be better. (though things worked amazingly well even though conflict area is high)

**Comment by zhuyifei1999** [comment]
One idea: if we enforce a custom subnet like 192.168.99.*, we could, in theory, allocate IPs server-side and request the user to change to a specific IP.

**Comment by zhuyifei1999** [comment]
Fixed mostly by d6351baa65d9044ec95f277a139a6f782f60c50f and 0d52b374ab3a7d3bc1fe1e80d831e47811a83025

**Comment by zhuyifei1999** [comment]
I not sure if 'constantly check for ARP packets' is worth the effort though :/

**Comment by ionizer999** [comment]
Probably not

**Comment by zhuyifei1999** [comment]
So I tried and a device like the switch would send an ARP probe to determine if an address is in use, and we will respond to the ARP probes. Hopefilly no device would forcefully use an IP via ARP announcements.

The collision of remote switch colliding with local devices has been fixed by the above two commits. The collision of a local switch against a remote switch has been fixed in cd817dc5 with the server refusing to let the VM join the network and have the VM display a message. I think we can declare victory here.
